name: Lint
on:
  workflow_call:
    inputs:
      commitlint-args:
        required: true
        type: string
jobs:
  lint_commits:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 18
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Needs all PR's commits + 1
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: |
          yarn add @commitlint/cli @commitlint/config-conventional
          echo "module.exports = { extends: ['@commitlint/config-conventional'], rules: {'body-max-line-length': [2, 'always', 120] }};" > commitlint.config.js

      - name: Lint Commit Messages (conventional commit)
        run: yarn run commitlint ${{ inputs.commitlint-args }}
