on: [pull_request]
name: Pull Request validation

jobs:
  lint-commits:
    uses: ./.github/workflows/lint.yml
    with:
      commitlint-args: --from HEAD~$((${{ github.event.pull_request.commits }} - 1)) --to HEAD
